services:
  bot:
    build: .
    container_name: itoms_bot
    command: python bot.py
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always

  dashboard:
    build: .
    container_name: itoms_dashboard
    command: gunicorn -w 2 -b 0.0.0.0:7770 "dashboard.app:app"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "7770:7770"
    restart: always

