services:
  bot:
    build:
      context: .
      network: host
    container_name: itoms_bot
    command: python bot.py
    network_mode: host
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always

  dashboard:
    build:
      context: .
      network: host
    container_name: itoms_dashboard
    command: gunicorn -w 2 -b 0.0.0.0:7770 "dashboard.app:app"
    network_mode: host
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always